spring:
  logging:
    level:
      org.springframework.security: INFO
  flyway:
    enabled: true
    clean-on-validation-error: true
    baseline-on-migrate: true
  application:
    name: Sharpshap
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    password:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      endle:
        jdbc:
          sql:
            SqlExceptionHelper: DEBUG
      springframework:
        security: DEBUG
      hibernate:
        tool:
          hbm2ddl: TRACE
        SQL: DEBUG
jwt:
  access-key-secret: ${JWT_SECRET_ACCESS_KEY}
  refresh-key-secret: ${JWT_SECRET_REFRESH_KEY}